# render.yaml
services:
  - type: web
    name: springboot-emp
    env: java
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/SpringBootEmp-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod